# Identificação do Projeto
sonar.projectKey=crud_basico
sonar.projectName=CRUD de Receitas (Task 2)
sonar.projectVersion=1.0

# Configurações da Linguagem
sonar.python.version=3.12

# Diretórios a serem analisados (código fonte)
# A pasta crud já engloba o tests.py, portanto não precisamos do "sonar.tests"
sonar.sources=crud,core

# Caminho para o relatório de cobertura gerado pelo pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

# Exclusões (não analisar estes ficheiros de todo)
sonar.exclusions=**/migrations/**,**/__pycache__/**,manage.py,core/asgi.py,core/wsgi.py

# Excluir o ficheiro de testes da cobrança de cobertura de código
sonar.coverage.exclusions=crud/tests.py

# URL do SonarQube local
sonar.host.url=http://localhost:9000