# Identificação do Projeto
sonar.projectKey=crud_basico
sonar.projectName=CRUD de Receitas (Task 2)
sonar.projectVersion=1.0

# Configurações da Linguagem
sonar.python.version=3.12

# Diretórios a serem analisados (código fonte)
sonar.sources=crud,core
# Diretório dos testes
sonar.tests=crud/tests.py

# Caminho para o relatório de cobertura gerado pelo pytest-cov
sonar.python.coverage.reportPaths=coverage.xml

# Exclusões (não contabilizar isto nas estatísticas)
sonar.exclusions=**/migrations/**,**/__pycache__/**,manage.py,core/asgi.py,core/wsgi.py

# URL do SonarQube local
sonar.host.url=http://localhost:9000