# Generated by Django 6.0.3 on 2026-03-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id_receita', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_receita', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
