# Generated by Django 6.0.3 on 2026-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_receita_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='porcoes',
            field=models.PositiveIntegerField(default=1, verbose_name='Porções'),
        ),
    ]
