# Generated by Django 6.0.3 on 2026-06-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_receita_porcoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='porcoes',
        ),
    ]
