# Generated by Django 6.0.3 on 2026-06-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_teste_receita_porcoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste',
        ),
    ]
