# Generated by Django 6.0.3 on 2026-06-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_delete_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='porcoes',
        ),
    ]
