# Generated by Django 6.0.3 on 2026-06-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_remove_receita_porcoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='teste',
            fields=[
                ('id_teste', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
